config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :endpoints

  root "endpoints#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/endpoint.rb
# == Schema Information
#
# Table name: endpoints
#
#  id                :bigint           not null, primary key
#  max_response_time :integer          not null
#  name              :string           not null
#  period            :integer          not null
#  url               :string           not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Endpoint < ApplicationRecord

  has_one :status, class_name: "EndpointStatus", dependent: :destroy
  has_many :history_days, class_name: "HistoryDay", dependent: :destroy
  validates :name, presence: true
  validates :url, presence: true, format: URI::DEFAULT_PARSER.make_regexp(%w[http https])
  validates :period, presence: true, numericality: { greater_than: 0 }
  validates :max_response_time, presence: true, numericality: { greater_than: 0 }

  after_update_commit -> { broadcast_replace_to "endpoints" }
  after_create_commit -> { broadcast_prepend_to "endpoints" }
  after_destroy_commit -> { broadcast_remove_to "endpoints" }
end

app/models/endpoint_status.rb
# == Schema Information
#
# Table name: endpoint_statuses
#
#  id            :bigint           not null, primary key
#  response_time :integer
#  status        :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  endpoint_id   :bigint           not null
#
# Indexes
#
#  index_endpoint_statuses_on_endpoint_id  (endpoint_id)
#
# Foreign Keys
#
#  fk_rails_...  (endpoint_id => endpoints.id)
#
class EndpointStatus < ApplicationRecord
  belongs_to :endpoint, touch: true
end

app/models/history_day.rb
# == Schema Information
#
# Table name: history_days
#
#  id                    :bigint           not null, primary key
#  average_response_time :integer
#  date                  :date
#  failed_requests_count :integer
#  request_count         :integer
#  status                :string
#  total_response_time   :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  endpoint_id           :bigint           not null
#
# Indexes
#
#  index_history_days_on_endpoint_id  (endpoint_id)
#
# Foreign Keys
#
#  fk_rails_...  (endpoint_id => endpoints.id)
#
class HistoryDay < ApplicationRecord
  belongs_to :endpoint
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/endpoints_controller.rb
class EndpointsController < ApplicationController
  def index
    @endpoints = Endpoint.includes(:history_days, :status).order(created_at: :desc)
    @endpoint = Endpoint.new
  end

  def destroy
    endpoint = Endpoint.find(params[:id])
    endpoint.destroy
  end

  def create
    endpoint = Endpoint.new(endpoint_params)
    if endpoint.save
      PingEndpointJob.perform_async(endpoint.id)
    end
  end

  private

  def endpoint_params
    params.require(:endpoint).permit(:name, :url, :period, :max_response_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_status(status)
    case status
    when "operational"
      color_class = "text-emerald-500 bg-emerald-100/60 dark:bg-gray-800"
      label = "Operational"
    when "degraded"
      color_class = "text-yellow-500 bg-yellow-100/60 dark:bg-gray-800"
      label = "Degraded"
    when "incident"
      color_class = "text-red-500 bg-red-100/60 dark:bg-gray-800"
      label = "Incident"
    else
      color_class = "text-gray-500 bg-gray-100/60 dark:bg-gray-800"
      label = "Unknown"
    end

    content_tag(:div, class: "inline-flex items-center px-3 py-1 rounded-full gap-x-2 #{color_class}") do
      content_tag(:h2, label, class: "text-sm font-normal")
    end
  end

  def render_history_day(history_day)
    case history_day.status
    when "operational"
      color_class = "bg-emerald-500"
    when "degraded"
      color_class = "bg-yellow-500"
    when "incident"
      color_class = "bg-red-500"
    else
      color_class = "bg-gray-500"
    end

    content_tag(:button, class: "has-tooltip h-10 w-2 rounded-full flex-1 #{color_class}") do
      content_tag(:div, class: "tooltip rounded shadow-lg p-1 bg-gray-100 text-blue-600 -mt-28") do
        content_tag(:div) do
          content_tag(:div) { "Date: #{history_day.date}" } +
            content_tag(:div) { "Average response time: #{history_day.average_response_time}" } +
            content_tag(:div) { "Failed requests: #{history_day.failed_requests_count}" } +
            content_tag(:div) { "Day status: #{history_day.status}" }
        end
      end
    end
  end
end

app/views/endpoints/_endpoint.html.erb
<tr id="endpoint_<%= endpoint.id %>">
  <td class="px-4 py-4 text-sm font-medium text-gray-200 whitespace-nowrap">
    <div class="inline-flex items-center gap-x-3">
      <span><%= endpoint.name %></span>
    </div>
  </td>
  <td class="px-4 py-4 text-sm text-gray-300 whitespace-nowrap">
    <%= endpoint.updated_at || 'Never' %>
  </td>
  <td class="px-4 py-4 text-sm font-medium text-gray-700 whitespace-nowrap">
    <%= render_status(endpoint.status&.status) %>
  </td>
  <td class="px-4 py-4 text-sm text-gray-500 dark:text-gray-300 whitespace-nowrap">
    <div class="flex items-center gap-x-2">
      <div>
        <h2 class="text-sm font-medium text-gray-800 dark:text-white ">
          <%= endpoint.status&.response_time %>/<%= endpoint.max_response_time %>
        </h2>
      </div>
    </div>
  </td>
  <td class="px-4 py-4 text-sm text-gray-500 dark:text-gray-300 whitespace-nowrap">
    <% endpoint.history_days.order(:date).each do |day| %>
      <%= render_history_day(day) %>
    <% end %>
  </td>
  <td class="px-4 py-4 text-sm whitespace-nowrap">
    <div class="flex items-center gap-x-6">
      <%= button_to "Remove", endpoint_path(endpoint),
                    method: :delete,
                    remote: true,
                    form: { data: { turbo_confirm: 'Are you sure?' } },
                    class: "text-red-500 transition-colors duration-200 hover:text-indigo-500 focus:outline-none" %>

    </div>
  </td>
</tr>

app/views/endpoints/index.html.erb
<%= turbo_stream_from "endpoints" %>
<section class="container px-4 mx-auto">
  <%= form_with model: @endpoint, class: "mb-3 xl:flex xl:justify-between" do |form|  %>
    <%= form.text_field :name, placeholder: :name, class: "rounded" %>
    <%= form.text_field :url, placeholder: :url, class: "rounded" %>
    <%= form.text_field :max_response_time, placeholder: :max_response_time, class: "rounded" %>
    <%= form.text_field :period, placeholder: :request_period, class: "rounded" %>
    <%= form.submit :add, class: "focus:ring-2 focus:ring-offset-2 focus:ring-indigo-600
   px-6 py-3 bg-indigo-700 hover:bg-indigo-600 focus:outline-none rounded text-white text-sm" %>
  <% end %>
  <div class="flex flex-col">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden border border-gray-700 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
            <thead class="bg-gray-50 bg-gray-800">
            <tr>
              <th scope="col" class="py-3.5 px-4 text-sm font-normal text-left rtl:text-right text-gray-400">
                <div class="flex items-center gap-x-3">
                  Endpoint
                </div>
              </th>

              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-400">
                Last checked
              </th>

              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-400">
                Status
              </th>

              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-400">
                Response Time
              </th>

              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-400">
                History (Last 7 Days)
              </th>

              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-400">
                Actions
              </th>
            </tr>
            </thead>
            <tbody class="divide-y divide-gray-700 bg-gray-900" id="endpoints">
              <%= render partial: "endpoint", collection: @endpoints %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Endpoint Monitoring" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-700">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>